# It is here as an example, and if the user wants to change the default
# settings they should first make a copy and edit that.

# Path to the fits file of simulation data.
data_path: 'sim_data/cl19.fits'

# This is where the user chooses the filter of the imager
imager_filter: 'g'

mass_to_light_ratio:
    g: 5
    r: 5

# The luminosity distance between the observer and the target galaxy.
galaxy_distance: 10.

# The resolution of the simulation(parsec / pixel).
sim_pc_pixel: 170 

# The baryonic mass of simulation particles (1e5 * Msol/h).
particle_baryonic_mass_sim: 9.6031355

# Cosmological parameters.
hubble_constant: 0.705  # (Km/s)/Mpc
Omega_Lambda: 0.727
Omega_0: 0.273
redshift: 0